### ISSUE TITLE
Blacklist persisted only once

### ISSUE THREAD

**Issue by MaximumViciousDeer** [yeriomin/YalpStore#540]
Yalp store version 0.43 only remembers the blacklist the first time i update it in the app right after it is installed. If I ever try to change the blacklist again afterwards it is lost after closing the app (no persistence).
This means that every time I want to add a new app to the blacklist I need to reinstall Yalp store.
Any suggestions?

**Comment by Lorodion** [comment]
This used to work before but it no longer does and I'm not sure what caused it.
I'm on Lineage OS 15.1 with microG on Google Pixel 1.

**Comment by yeriomin** [comment]
This issue resembles #520. I cannot reproduce this. Version 0.44 is out, so please try it, but I don't think it is going to help as I didn't change anything related to blacklists. I would appreciate any additional details/logs.

> This used to work before but it no longer does

Please, be specific if you can.

**Comment by backamblock** [comment]
Hey, the fix from the old version still works.. !
1. open yalp, blacklist all you want from start screen
2. search for updates
3. when finished, close app AND remove from "recent apps"
4. restart = blacklist still valid
5. reboot =blackilist still valid

**Comment by MaximumViciousDeer** [comment]
> This issue resembles #520. I cannot reproduce this. Version 0.44 is out, so please try it, but I don't think it is going to help as I didn't change anything related to blacklists. I would appreciate any additional details/logs.
> 
> > This used to work before but it no longer does
> 
> Please, be specific if you can.

I thought the problem started after I installed a specific app but uninstalling the suspected apps didn't change anything, so don't know what causes it... Where can I find logs?

> Hey, the fix from the old version still works.. !
> 
>     1. open yalp, blacklist all you want from start screen
> 
>     2. search for updates
> 
>     3. when finished, close app AND remove from "recent apps"
> 
>     4. restart = blacklist still valid
> 
>     5. reboot =blackilist still valid

Thanks, this actually works. (for all apps except for Yalp Store itself)

**Comment by haroon-ali** [comment]
I was suffering from the same bug, now it's solved with 0.45 contemporary.

**Comment by MaximumViciousDeer** [comment]
I can find the "Version 0.45-legacy" on the F-Droid website but it does not show up in my F-Droid app. I guess it is not compatible with my phone?

**Comment by emacsomancer** [comment]
I still have this issue. And how does one remove an app from recent apps?
